version: '3.1'

services:
  elasticsearch:
    image: elasticsearch:7.17.22
    container_name: elasticsearch
    networks:
      - somenetwork
    ports:
      - "9200:9200"
      - "9300:9300"
    deploy:
      resources:
        limits:
          memory: 1GB
    environment:
      - discovery.type=single-node

networks:
  somenetwork:
    driver: bridge

